language: lua

dist: trusty

addons:
  apt:
    packages:
    - libfcgi-dev
    - lua5.1
    - luarocks

script:
- command -v lua
# - lua hello.lua
- lua -e 'print("Hello World")'
- command -v luarocks
- sudo -H luarocks install luasocket
# Error: Your user does not have write permissions in /usr/local/lib/luarocks/rocks 
# -- you may want to run as a privileged user or use your local tree with --local.
- find /usr/local -name socket.lua
- lua -e 'require "socket"'
- sudo -H luarocks install luasec
- lua -e 'require "luasec"'


after_script:
- sudo -H luarocks install wsapi
- lua -e 'require "wsapi"'
- sudo -H luarocks install wsapi-xavante
- lua -e 'require "wsapi.xavante"'
- apt-cache policy libfcgi-dev
- apt-cache policy libfcgi0ldbl
- sudo -H luarocks install wsapi-fastcgi
- lua -e 'require "wsapi.fastcgi"'
