language: lua

dist: trusty

addons:
  apt:
    packages:
    - libfcgi-dev # wsapi-fastcgi
    - libssl-dev # luasec
    - lua5.1
    - lua-sec
    - luarocks
    - openssl # luasec


before_install:
- command -v lua
- command -v luarocks


install:
- sudo -H luarocks install luasocket
# Error: Your user does not have write permissions in /usr/local/lib/luarocks/rocks 
# -- you may want to run as a privileged user or use your local tree with --local.
- sudo -H luarocks install wsapi
- lua -e 'require "wsapi"'
- sudo -H luarocks install wsapi-xavante
- lua -e 'require "wsapi.xavante"'


before_script:
- find /usr/local -name socket.lua


script:
- lua -e 'print("Hello World")'
- lua -e 'require "socket"'
- lua -e 'require "ssl"'


after_script:
# - sudo -H luarocks install luasec OPENSSL_DIR=/usr/lib/i386-linux-gnu
- sudo -H luarocks install luasec OPENSSL_DIR=/usr/lib # ssl
- apt-cache policy libfcgi-dev
- apt-cache policy libfcgi0ldbl
# - sudo -H luarocks install wsapi-fastcgi
- sudo -H luarocks install wsapi-fcgi
- lua -e 'require "wsapi.fastcgi"'
