language: lua

dist: trusty

addons:
  apt:
    packages:
    - libfcgi-dev # wsapi-fastcgi
    - libssl-dev # luasec
    - lua5.1
    - lua-sec
    - luarocks
    - openssl # luasec


before_install:
- command -v lua
- command -v luarocks


install:
- sudo -H luarocks install luasocket # check if it does replace one installed by debian lua-sec
# Error: Your user does not have write permissions in /usr/local/lib/luarocks/rocks 
# -- you may want to run as a privileged user or use your local tree with --local.
- lua -e 'require "socket"'
- sudo -H luarocks install wsapi
- lua -e 'require "wsapi"'
- sudo -H luarocks install wsapi-xavante
- lua -e 'require "wsapi.xavante"'
- sudo -H luarocks install wsapi-fcgi
- lua -e 'require "wsapi.fastcgi"'


before_script:
- find /usr/local -name socket.lua


script:
- lua -e 'print("Hello World")'
- lua -e 'require "ssl"'


after_script:
- luarocks list
# - sudo -H luarocks install luasec OPENSSL_DIR=/usr/lib/i386-linux-gnu
# - sudo -H luarocks install luasec OPENSSL_DIR=/usr/lib/x86_64-linux-gnu # ssl # Needs OpenSSL version 1.1.0 not available on ubuntu trusty
- sudo -H luarocks install luasec 0.5-1 OPENSSL_DIR=/usr/lib/ssl # ssl
- ls --color /usr/lib/ssl
- ls --color /usr/lib/*/libssl.*
# - find / -name libssl.\*
- apt-cache policy libfcgi-dev
- apt-cache policy libfcgi0ldbl
